// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4w-V5-eVXW0fVoQWtiKbSL1q9n9OxEow',
    appId: '1:111884703674:web:1ee6daf867b271305b2f83',
    messagingSenderId: '111884703674',
    projectId: 'mynotes-demo-app-14b28',
    authDomain: 'mynotes-demo-app-14b28.firebaseapp.com',
    storageBucket: 'mynotes-demo-app-14b28.appspot.com',
    measurementId: 'G-C4JLSBHQQS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5UzHx4yEpxWiD_Wwo8r1pBuM9r7mi53E',
    appId: '1:111884703674:android:079b330af688a1a25b2f83',
    messagingSenderId: '111884703674',
    projectId: 'mynotes-demo-app-14b28',
    storageBucket: 'mynotes-demo-app-14b28.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNRkBXrvmtp03aOUsiSiW-Pwq-QOhPvik',
    appId: '1:111884703674:ios:4a5c2c242af8cd785b2f83',
    messagingSenderId: '111884703674',
    projectId: 'mynotes-demo-app-14b28',
    storageBucket: 'mynotes-demo-app-14b28.appspot.com',
    iosClientId: '111884703674-96rul1ua5pm3jjo6qgje0cdl8m371m5p.apps.googleusercontent.com',
    iosBundleId: 'com.dinurasathsindu.flutterpractice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNRkBXrvmtp03aOUsiSiW-Pwq-QOhPvik',
    appId: '1:111884703674:ios:03e50a2fdb0253f95b2f83',
    messagingSenderId: '111884703674',
    projectId: 'mynotes-demo-app-14b28',
    storageBucket: 'mynotes-demo-app-14b28.appspot.com',
    iosClientId: '111884703674-qk1m1vknntbrtt260m19c3i4thr1djrv.apps.googleusercontent.com',
    iosBundleId: 'com.dinurasathsindu.flutterpractice.RunnerTests',
  );
}
